### ISSUE TITLE
This is a desperate method of contacting you (blizzy78)

### ISSUE THREAD

**Issue by dRoskar** [blizzy78/ksp-precisenode#20]
Greetings, I've been looking everywhere for any contact information on you but there is nothing to be found. Not even on your website. So This is the only option I have to speak to you.

A while ago you wrote a blog - 
http://www.subshell.com/en/subshell/blog/Implementing-a-Color-Picker-Dialog-With-Canvas-and-GWT100.html

and published the source code. I would like to ask your permission to use this code in my diploma, please.

**Comment by blizzy78** [comment]
Uh, now that's unexpected here :)

Sure, please go ahead. Although I'm sure there are better solutions that have popped up over the years.

**Comment by dRoskar** [comment]
Thank you!
