### ISSUE TITLE
Complete rewrite (I'm serious)

### ISSUE THREAD

**Issue by radistmorse** [blizzy78/ksp-precisenode#24]
Hi there,

I tried to write in the KSP forum, which would be a more appropriate place for thinks like this, but it's turned out to be pre-moderated, so screw it.

So I downloaded your mode, used it a little, then I wanted to tweak it a little and... well... I ended up pretty much rewriting it from scratch :)

Now I'm kinda in a loss what to do with it. Sending it as a pull request is pretty pointless, since it's a rewrite, and posting it as a separate mod will confuse everyone, since the functionality is pretty much the same.

These are the differences that I introduces in my version:
*    Complete restructure of the project: I removed half of the code from the project. Maybe more.
*    Rework of the main window UI: all the "show this" and "show that" options are now present at the main window as buttons.
*    The text fields of the main window became non-editable. I never found the ability to edit the numbers directly usable, and it messed with hotkeys. Much.
*    The buttons and the hotkeys became repeatable, so you don't need to click them furiously anymore. Just press'em, and after a short delay they'll start work continuously.

What was removed:
*    All the windows except for main one and the keybinding were axed. They are redundant IMO.
*    Intuitive node functionality was removed. I mean, it's a totally unrelated mod, what it even has to do with the precise edit?
*    Merging nodes together. I can't think of a single situation when I would want to merge two nodes.
*    MS/MR. Never used it, but maybe it's just me...

What was added:
*    Integration with the alarm plugin: you can add an alarm 10 minutes prior the maneuver. This integration is optional, if the plugin is not installed, the button is just inactive.
*    Selection of the node by clicking the gizmo.

So, your advise: what should I do with the code? Are you interested in a completely new version of the same? :)

**Comment by blizzy78** [comment]
I hope you don't get this the wrong way, and I don't want to sound rude and all of that, but ...

> Are you interested in a completely new version of the same?

No, not really.

I might be interested in parts of your work, should you be willing to share as pull requests.

**Comment by radistmorse** [comment]
Well, that's the problem, being a complete rewrite it's hard to pick out some part and make a pull request out of it. I already published my version at https://github.com/radistmorse/KSPPreciseManeuver if you want to look
