### ISSUE TITLE
Download link borken

### ISSUE THREAD

**Issue by arechsteiner** [blizzy78/ksp-precisenode#28]
The download link in the main forum post is broken:

http://forum.kerbalspaceprogram.com/index.php?/topic/44129-120-precise-node-124-precisely-edit-your-maneuver-nodes/

Maybe this could be solved through GitHub releases?

**Comment by blizzy78** [comment]
@linuxgurugamer is now managing Precise Node, please see this post: http://forum.kerbalspaceprogram.com/index.php?/topic/44129-120-precise-node-124-precisely-edit-your-maneuver-nodes/&do=findComment&comment=3083979

**Comment by arechsteiner** [comment]
Maybe you could edit the forum post though? It's still the top Google result for "kerbal precise node" and there is no hint that there is a [new version](http://forum.kerbalspaceprogram.com/index.php?/topic/161855-13-precise-node-continued-precisely-edit-your-maneuver-nodes/) somewhere else.
